<div>
	<div id="liverTestedDiv" class="pageContent">
		<div class="panelBar">
			<ul class="toolBar">
<#--				<li><a class="add" href="" target="dialog" rel="save" width="550" height="620"><span>查看详细</span></a></li>-->
				<li><a class="delete" onclick="deleteLiverTested()" title="确定要删除吗?"><span>删除</span></a></li>
			</ul>
		</div>
		<table class="table" style="overflow: scroll; width: 3000px;">
			<thead>
			<tr>
				<#--              <th orderField="id"  >ID</th>-->
				<th>凝血酶原时间</th>
				<th>凝血酶原活动度</th>
				<th>凝血酶原国际标准化比值</th>
				<th>凝血酶时间</th>
				<th>活化部分凝血活酶时间</th>
				<th>纤维蛋白原</th>
				<th>D-二聚体</th>
				<th>钾</th>
				<th>钠</th>
				<th>氯</th>
				<th>钙</th>
				<th>镁</th>
				<th>磷</th>
				<th>铁</th>
				<th>二氧化碳结合力</th>
				<th>丙氨酸氨基转移酶</th>
				<th>天门冬氨酸氨基转移酶</th>
				<th>总蛋白</th>
				<th>白蛋白</th>
				<th>总胆红素</th>
				<th>直接胆红素</th>
				<th>前白蛋白</th>
				<th>碱性磷酸酶</th>
				<th>腺苷脱氨酶</th>
				<th>甘胆酸</th>
				<th>y-谷氨酰基转移酶</th>
				<th>唾液酸</th>
				<th>肌酸激酶</th>
				<th>肌酸激酶同功酶</th>
				<th>乳酸脱氢酶</th>
				<th>a-羟丁酸脱氢酶</th>
				<th>淀粉酶</th>
				<th>胆碱脂酶</th>
				<th>尿素氮</th>
				<th>肌酐</th>
				<th>尿酸</th>
				<th>β2-微球蛋白</th>
				<th>胱抑素C</th>
				<th>葡萄糖</th>
				<th>总胆固醇</th>
				<th>甘油三酯</th>
				<th>高密度脂蛋白胆固醇</th>
				<th>低密度脂蛋白胆固醇</th>
				<th>游离脂肪酸</th>
				<th>小而密低密度脂蛋白胆固醇</th>
				<th>间接胆红素</th>
				<th>球蛋白</th>
				<th>S/L</th>
				<th>阴离子间隙</th>
				<th>白球比</th>
				<th>B型钠尿肽前体</th>
				<th>超敏肌钙蛋白T</th>
				<th>癌胚抗原</th>
				<th>神经元特异性烯醇化酶</th>
				<th>细胞角蛋白19片段</th>
				<th>胃泌素释放肽前体</th>
				<th>鳞状细胞癌相关抗原</th>
				<th>游离三碘甲状原氨酸</th>
				<th>游离甲状腺素</th>
				<th>促甲状腺激素</th>
				<th>甲状腺球蛋白抗体</th>
				<th>甲状腺球蛋白</th>
			</tr>
			</thead>
			<tbody>
			<#if list?? && (list?size > 0)>
				<#list list as liverTested>
					<tr onclick="selectLiverTested('${liverTested.id}')" target="sid" rel="${liverTested.id}">
					<td>${liverTested.prothrombinTime!}</td>
					<td>${liverTested.prothrombinActivity!}</td>
					<td>${liverTested.prothrombinStandardRatio!}</td>
					<td>${liverTested.thrombinTime!}</td>
					<td>${liverTested.thrombokinaseTime!}</td>
					<td>${liverTested.fibrinogen!}</td>
					<td>${liverTested.dDimer!}</td>
					<td>${liverTested.potassium!}</td>
					<td>${liverTested.natrium!}</td>
					<td>${liverTested.chlorin!}</td>
					<td>${liverTested.calcium!}</td>
					<td>${liverTested.magnesium!}</td>
					<td>${liverTested.phosphorus!}</td>
					<td>${liverTested.ferrumiron!}</td>
					<td>${liverTested.co2Cohesion!}</td>
					<td>${liverTested.aat!}</td>
					<td>${liverTested.aspartateAminoTransferase!}</td>
					<td>${liverTested.totalProtein!}</td>
					<td>${liverTested.albumin!}</td>
					<td>${liverTested.totalBilirubin!}</td>
					<td>${liverTested.directBilirubin!}</td>
					<td>${liverTested.frontAlbumin!}</td>
					<td>${liverTested.alkalinePhosphatase!}</td>
					<td>${liverTested.adenosineDeaminase!}</td>
					<td>${liverTested.glycocholicAcid!}</td>
					<td>${liverTested.glutamylTransferase!}</td>
					<td>${liverTested.acylneuraminate!}</td>
					<td>${liverTested.creatineKinase!}</td>
					<td>${liverTested.isoenzymesCreatineKinase!}</td>
					<td>${liverTested.lacticDehydrogenase!}</td>
					<td>${liverTested.aHbd!}</td>
					<td>${liverTested.amylase!}</td>
					<td>${liverTested.cholinesterase!}</td>
					<td>${liverTested.ureaNitrogen!}</td>
					<td>${liverTested.creatinine!}</td>
					<td>${liverTested.uricAcid!}</td>
					<td>${liverTested.microglobulin!}</td>
					<td>${liverTested.cystatinC!}</td>
					<td>${liverTested.glucose!}</td>
					<td>${liverTested.totalCholesterin!}</td>
					<td>${liverTested.triglyceride!}</td>
					<td>${liverTested.hdlCh!}</td>
					<td>${liverTested.cLdl!}</td>
					<td>${liverTested.freeFattyAcid!}</td>
					<td>${liverTested.smallCldl!}</td>
					<td>${liverTested.indirectBilirubin!}</td>
					<td>${liverTested.globulin!}</td>
					<td>${liverTested.sl!}</td>
					<td>${liverTested.ag!}</td>
					<td>${liverTested.albuminGlobulinRatio!}</td>
					<td>${liverTested.proBnp!}</td>
					<td>${liverTested.troponinT!}</td>
					<td>${liverTested.cAntigen!}</td>
					<td>${liverTested.neureNse!}</td>
					<td>${liverTested.cytokeratin19!}</td>
					<td>${liverTested.grpProsoma!}</td>
					<td>${liverTested.epidermoidCarcinoma!}</td>
					<td>${liverTested.ft3!}</td>
					<td>${liverTested.ft!}</td>
					<td>${liverTested.tsh!}</td>
					<td>${liverTested.tga!}</td>
					<td>${liverTested.thyroprotein!}</td>
					</tr>
				</#list>
			</#if>
			</tbody>
		</table>
	</div>
</div>